package ea.sports.fut.model

data class Identity (val externalRefType : String,
            val externalRefValue : String,
            val pidId : String,
            val email : String,
            val emailStatus : String,
            val strength : String,
            val dob : String,
            val country : String,
            val language : String,
            val locale : String,
            val status : String,
            val reasonCode : String,
            val tosVersion : String,
            val parentalEmail : String,
            val thirdPartyOptin : String,
            val globalOptin : String,
            val dateCreated : String,
            val dateModified : String,
            val lastAuthDate : String,
            val registrationSource : String,
            val authenticationSource : String,
            val showEmail : String,
            val discoverableEmail : String,
            val anonymousPid : String,
            val underagePid : String,
            val defaultBillingAddressUri : String,
            val defaultShippingAddressUri : String,
            val passwordSignature : String)